### ISSUE TITLE
[PROJECTS] Osu! Lookup

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#12]
### Command with multiple methods reaching the respective endpoints:
[Wiki](https://github.com/ppy/osu-api/wiki)
#### User
1. `/api/get_user`
   - Get general information of a user
2. `/api/get_user_best`
   - Get user's best scores
3. `/api/get_user_recent`
   - Get user recent games

#### Beatmap
1. `/api/get_beatmaps`
   - Get information on a beatmap
2. `/api/get_scores`
   - Get top 10 of the beatmap (Combined with first item)

Ninja edit:
Current progress can be found [`here`](https://github.com/TheDragonProject/Kanna-Kobayashi/compare/ec9152d144181c76578a0b6569723022021eec40...osu).

**Comment by SpaceEEC** [comment]
Closed with https://github.com/TheDragonProject/Kanna-Kobayashi/commit/ca115a813d7572e033ce0fdf33e7c0bd053d2db0
