### ISSUE TITLE
[Feature] Leaderboard

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#15]
## Use
With Arguments | Without Arguments
-------------------|----------------------
Top 30 | Top 30 on level 
everything listed on the ProfileCommand that is possible to enumerate | *maybe* make it possible to see their profiles (could be really neat)

> *Basically if you use the command with arguments you can choose to see how much dragon scale, coins, level, etc.*

**Comment by SpaceEEC** [comment]
Completed with:
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/62f1c4e1d8f361bcf5f58ee5e4d42bee6e200e64
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/2f7508fefc75f56020ab8941e5a7ab8bced52e11
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/7404efeed6c72600fcde450a182b5877c018e1d0
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/9d5adeca60ae3d0ba64a7b7211fcf2e93bd5a87b
