### ISSUE TITLE
[Enchancement] Remake the Market

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#17]
## Command
> Paginate the existing items and badges and make it able to see the information of each item or badge on that list, when you look the info, have the option to buy it if it is buyable, or to sell if it sellable
>
>Dragon Scale i am thinking of making it unbayable but sellable, so we make a special market for it (It can be really neat as we could make global events with that market and attract more grinders)
>
>_Obs: I think we should separate Items from Badges, without args be items as most look for that, or make it toggable with a reaction_

## Items
> Have detailed descriptions about them, a.k.a. what it is for (if there is any use of course)
>
> Show which command they interact with if they do (I am planning to make some items to work on commands), maybe we can add that later if you want

## Badges
> Make them buyable after the user met a certain quota, we can literally make it function based (and will save a lot of time tbh

**Comment by SpaceEEC** [comment]
Completed with:
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/0b06627c835ac3c8f4b110b437cbc40096ab82ad
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/156e5223662cc8b1cb01024717c2e966dbe1b581
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/0cea9fe1b2a96d789f4738fa139a312477f215bd
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/a345d8396a361217f55337f3f889d422b6de6261
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/33e7d6b70541bed057c5b9dc446a14aa1ace733f
- https://github.com/TheDragonProject/Kanna-Kobayashi/commit/263b24500f9568006e44c2f605e4d1fa9e2b9bf0
