### ISSUE TITLE
[WIP] Patreon

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#18]
## Tier
> Every one dollar donated the user should have plus patreon tier, aside from 1$, it'll give 2
> 
> Acess to some special commands for patreons
>
> Unique category on help command, to well, attract users to pledge
>
> On Daily we get that amount of coins and multiply by their Tier, same goes for Weekly

> _Obs: more stuff will come on future, but Patreon Tier is vital for it_

**Comment by SpaceEEC** [comment]
(Mostly) completed in various commits
