### ISSUE TITLE
[WIP] Dragon Scale

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#19]
## Special Market
> Every item that has a rarity above Dragon Scale's rarity is bought with Dragon Scales, the amount of coins the item costs will be the amount of Dragon Scales it costs, every Dragon Scale costs 1000 coins.

> _Obs: Everything up from Dragon's Scale rarity should not be listed on common market_

**Comment by SpaceEEC** [comment]
See #17
