### ISSUE TITLE
[Feature] Weekly

### ISSUE THREAD

**Issue by WizardLink** [TheDragonProject/Kanna-Kobayashi#20]
## Use
> User gets one Dragon Scale multiplied with their patreon tier, can be only used once a week.
>
> Users who did not upvote Kanna on discordbots.org cannot use the weekly command

**Comment by SpaceEEC** [comment]
Completed with
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/8c55efea71348998289ca679d6d56defaa2c3a00
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/45522d197134f88e54a91a5e5006595f50232faa
https://github.com/TheDragonProject/Kanna-Kobayashi/commit/d65680d6e74e2e94a7e48a94421731a0d44fa7f6
