### ISSUE TITLE
[BUG HUNT] - Guildinfo command contains spelling mistake in usage

### ISSUE THREAD

**Issue by CaptMU167** [TheDragonProject/Kanna-Kobayashi#57]
I was looking through help and I witnessed the 'guildinfo' spelt as 'guilinfo'.
I used kanna help, and moved to the page with guildinfo on it.
https://cdn.discordapp.com/attachments/299632639600492556/641363798267265026/unknown.png
don't know if this is the kind of link you want but here ^^
-CaptMU#2702

**Comment by wizardlink** [comment]
Please, always use our template for issues, if it does not fits just remove such line. Also use `[BUG HUNT] -` in the name next time.

**Comment by wizardlink** [comment]
Also, edit your message later to put your Discord tag there.
