### ISSUE TITLE
[BUG HUNT] - DoIt command has invalid usage

### ISSUE THREAD

**Issue by digitwolfs** [TheDragonProject/Kanna-Kobayashi#58]
<img width="98" alt="Screen Shot 2019-11-05 at 21 06 46" src="https://user-images.githubusercontent.com/46846958/68242507-f3eb9200-0010-11ea-988c-b243dfceacea.png">

 I did k!help and on page 3 it said kanna doit for the k!dance comment

1. I typed k!help
2. Then pressed on the arrow 2 times
3. Then i saw "Kanna doit" above the k!dance command.

-Digit!#5125

**Comment by wizardlink** [comment]
Please, always use our template for issues, if it does not fits just remove such line. Also use `[BUG HUNT] - in the name next time`.

**Comment by SpaceEEC** [comment]
Relevant line of code, should be `doit`:
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/meme/doit.ts#L12
