### ISSUE TITLE
[BUG HUNT] - Blocklist command has incorrect desc., example, and usage

### ISSUE THREAD

**Issue by digitwolfs** [TheDragonProject/Kanna-Kobayashi#59]
<img width="127" alt="Screen Shot 2019-11-05 at 21 16 00" src="https://user-images.githubusercontent.com/46846958/68242854-9277f300-0011-11ea-8715-391fb81b4fc4.png">
<img width="131" alt="Screen Shot 2019-11-05 at 21 15 58" src="https://user-images.githubusercontent.com/46846958/68242856-9441b680-0011-11ea-8d82-baad6aa1d509.png">

## What went wrong
It says k!block twice while kanna blocklist is k!blocklist and kanna block is k!block

1. I did k!help
2. scrolled through the pages
3. saw it said k!block under kanna blocklist instead of k!blocklist

-Digit#5125

**Comment by wizardlink** [comment]
Please, always use our template for issues, if it does not fits just remove such line. Also use `[BUG HUNT] - in the name next time`.

**Comment by SpaceEEC** [comment]
Now this is a blatant copy paste from the block command:
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/user/blocklist.ts#L14-L20
