### ISSUE TITLE
[BUG HUNT] - Gramatically incorrect 's in the help command

### ISSUE THREAD

**Issue by CaptMU167** [TheDragonProject/Kanna-Kobayashi#60]
![image](https://user-images.githubusercontent.com/57415893/68243502-8ccadf00-000a-11ea-8fb2-03b21218eb20.png)

Kiss's should be kiss'

## Reproducing the bug

I did kanna help kiss.
I saw a mistake.
-CaptMU#2702

**Comment by SpaceEEC** [comment]
Relevant line of code
https://github.com/Hydractify/kanna_kobayashi/blob/24000d8b8bf65823297d4ae7b6b56cf16a9ba073/src/commands/common/help.ts#L120

The same thing applies to all other commands where this grammatical rule applies to.
(And sometimes usernames too, fun!)

**Comment by wizardlink** [comment]
> Relevant line of code
> https://github.com/Hydractify/kanna_kobayashi/blob/24000d8b8bf65823297d4ae7b6b56cf16a9ba073/src/commands/common/help.ts#L120
> 
> The same thing applies to all other commands where this grammatical rule applies to.
> (And sometimes usernames too, fun!)

Well... Heck, but what can we do.

**Comment by wizardlink** [comment]
Please, always use our template for issues, if it does not fits just remove such line. Also use `[BUG HUNT] - in the name next time`. *Yes I will do this to every damn issue until you guys do it right.*
