### ISSUE TITLE
[BUG HUNT] - osuuser command has wrong command name in usage

### ISSUE THREAD

**Issue by digitwolfs** [TheDragonProject/Kanna-Kobayashi#61]
<img width="398" alt="Screen Shot 2019-11-05 at 21 30 03" src="https://user-images.githubusercontent.com/46846958/68243855-bfc5a080-0013-11ea-82d6-4a7882a70c54.png">
<img width="648" alt="Screen Shot 2019-11-05 at 21 30 14" src="https://user-images.githubusercontent.com/46846958/68243856-c0f6cd80-0013-11ea-9f57-9aa1efb9fea3.png">
## What went wrong

I was trying to lookup my osu user but k!osucommand did not work but k!osuuser did work.

1. I looked in k!help
2. Tried to use k!osucommand
3. It didn't work
4. Tried k!osuuser and it did work

-Digit#5125
[edit] k!help osucommand said osu command didnt exist.
<img width="705" alt="Screen Shot 2019-11-05 at 21 37 24" src="https://user-images.githubusercontent.com/46846958/68244181-91949080-0014-11ea-9eb6-5392f44340cd.png">

**Comment by wizardlink** [comment]
Please, always use our template for issues, if it does not fits just remove such line. Also use `[BUG HUNT] - in the name next time`.

**Comment by SpaceEEC** [comment]
Relevant line of code, probably an earlier name of the command I forgot to update:
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/info/osuuser.ts#L21

**Comment by wizardlink** [comment]
> 
> 
> Relevant line of code, probably an earlier name of the command I forgot to update:
> 
> https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/info/osuuser.ts#L21

So it is *basically* just a spelling mistake? If so I think the spelling tag would be more appropriate.
