### ISSUE TITLE
[BUG HUNT] - Despite k!marry being a command, I dont think its shown on the help page

### ISSUE THREAD

**Issue by Bicycle-Thief** [TheDragonProject/Kanna-Kobayashi#62]
#### Kanna Kobayashi

[Guild Info]()

## What went wrong

i just cant find it

## Reproducing the bug

i looked for it on the help menu but couldnt find it

i dont think i should post the whole help menu just take my word

**Comment by digitwolfs** [comment]
<img width="149" alt="Screen Shot 2019-11-05 at 21 39 08" src="https://user-images.githubusercontent.com/46846958/68244255-b5f06d00-0014-11ea-94e1-75028adc1ea8.png">
<img width="386" alt="Screen Shot 2019-11-05 at 21 39 38" src="https://user-images.githubusercontent.com/46846958/68244280-c7d21000-0014-11ea-8020-b37e67caf376.png">
sorry >.<

**Comment by Bicycle-Thief** [comment]
bruh

**Comment by wizardlink** [comment]
As @digitwolfs has shown, it does in fact exists.
