### ISSUE TITLE
[BUG HUNT] choice command splits at `or` while being part of a word

### ISSUE THREAD

**Issue by digitwolfs** [TheDragonProject/Kanna-Kobayashi#65]
## Information
v4.5.1

#### Kanna Kobayashi
[Guild Info]<img width="386" alt="Screen Shot 2019-11-06 at 16 29 33" src="https://user-images.githubusercontent.com/46846958/68315900-cfe38b80-00b8-11ea-8d9e-483d8ad5e03d.png">

## What went wrong

I was trying to use the command k!choice for k!choice memory or forgot and it gave me the answer y instead of the word memory itself.

## Reproducing the bug

1. I typed "k!choice memory or forgot"

-Digit#5125

**Comment by SpaceEEC** [comment]
Explanation of this bug:
This is because the word `or` is part of mem**or**y and our regex is missing word boundaries.

Relevant line of code:
https://github.com/Hydractify/kanna_kobayashi/blob/f0c3e6c25c2229d8b0a2309152cbe2178ad477a1/src/commands/fun/choose.ts#L25-L27
