### ISSUE TITLE
[BUG HUNT] catch command always uses 'bugs' instead of 'bug' for 1

### ISSUE THREAD

**Issue by CaptMU167** [TheDragonProject/Kanna-Kobayashi#75]
## What went wrong

I did 'kanna catch' and it said '1 bugs', while it should not be plural 'bugs' it should be singular 'bug'.

## Reproducing the bug

1. I did 'kanna catch'
2. I noticed a grammar mistake.

As reference, this is an image of the thing happening 
![image](https://user-images.githubusercontent.com/57415893/69485028-35ae7200-0e32-11ea-963b-6c578a07b9f2.png)

**Comment by SpaceEEC** [comment]
Relevant line of code: https://github.com/Hydractify/kanna_kobayashi/blob/5355af8c2db3265f7d816d7fc0d24fd76848a362/src/commands/fun/catch.ts#L51

It might be worth to split this up into multiple ifs instead of nesting ternaries though.
