### ISSUE TITLE
[BUG HUNT] 'error' spelt as 'errror' when an error occurs

### ISSUE THREAD

**Issue by CaptMU167** [TheDragonProject/Kanna-Kobayashi#76]
## What went wrong

The word 'error' is spelt as 'errror' in the error message.

## Reproducing the bug

1. I did 'kanna anime Dr. Stone'
2. Then, kanna replied with the error message, where I saw 'error' spelt wrong as 'errror', with three 'r's.

![image](https://user-images.githubusercontent.com/57415893/69486393-284db380-0e43-11ea-8634-026f391a5dc7.png)
![image](https://user-images.githubusercontent.com/57415893/69486399-2f74c180-0e43-11ea-8637-42150cc12ad7.png)

**Comment by SpaceEEC** [comment]
Line where the typo lies: https://github.com/Hydractify/kanna_kobayashi/blob/5355af8c2db3265f7d816d7fc0d24fd76848a362/src/structures/CommandHandler.ts#L360
