### ISSUE TITLE
[BUG HUNT] sayd errors out when prematurely deleting the message

### ISSUE THREAD

**Issue by CaptMU167** [TheDragonProject/Kanna-Kobayashi#77]
## What went wrong

I deleted my message before kanna could when using 'kanna sayd', therefore making kanna produce an error message.

## Reproducing the bug

1. I wrote 'kanna sayd hello'
2. Then I immediately deleted my message saying 'kanna sayd hello', before kanna could.
![image](https://user-images.githubusercontent.com/57415893/69486804-88465900-0e47-11ea-8a28-9ea387f77457.png)
![image](https://user-images.githubusercontent.com/57415893/69486807-909e9400-0e47-11ea-99f2-baf44936c100.png)

**Comment by SpaceEEC** [comment]
Relevant line of code: https://github.com/Hydractify/kanna_kobayashi/blob/5355af8c2db3265f7d816d7fc0d24fd76848a362/src/commands/fun/sayd.ts#L31
This probably needs to check for `Message#deleted` and have a `Promise#catch` making it ignore the "Unknown Message" error (while still throwing for other errors).
